# FOR DEVELOPMENT

# image with php and nginx
FROM webdevops/php-nginx-dev:alpine

WORKDIR /var/www/html

# Install PHP Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Remove Cache
RUN rm -rf /var/cache/apk/*

# copy the nginx configuration through
COPY nginx-dev.conf /opt/docker/etc/nginx/vhost.conf


## Useful commands
# cp .env.example .env
# composer install
# php artisan key:generate && php artisan config:cache